outpath:
    /mnt/d/ubuntu/freddie-test-output/

gurobi:
    license: /groups/share/modules/gurobi811/linux64/license/gurobi.lic
    timeout: 30
    recycle_models:
        - constant
        # - exons
        # - introns
        # - relative

samples:
    P000S000:
        - /mnt/d/ubuntu/freddie-test-data/H_sim.chr21.fastq
    P001S000:
        - /mnt/d/ubuntu/freddie-test-data/P001S000.chr21.fastq
    N_sim:
        - /mnt/d/ubuntu/freddie-test-data/N_sim.chr21.fastq
    # L_sim:
    #     - /mnt/d/ubuntu/freddie-test-data/L_sim.chr21.fastq
    # H_sim:
    #     - /mnt/d/ubuntu/freddie-test-data/H_sim.chr21.fastq

exec:
    sam_to_paf     : py/sam_to_paf.py
    gene_data      : py/gene_data.py
    polyA_and_gaps : py/polyA_and_gaps.py
    segment        : py/segment.py
    find_isoforms  : py/find_isoforms.py
    plot_isoforms  : py/plot_isoforms.py
    rand_index     : py/rand_index.py

genes:
    AR         : AR
    MYC        : MYC
    PLSCR3     : PLSCR3
    E2F1       : E2F1
    BLOC1S1    : BLOC1S1
    SRSF2      : SRSF2
    ATP5F1D    : ATP5F1D
    HAX1       : HAX1
    JTB        : JTB
    SLC50A1    : SLC50A1
    CTXN1      : CTXN1
    CEBPB      : CEBPB
    PGAM2      : PGAM2
    GADD45GIP1 : GADD45GIP1
    SFN        : SFN
    NDUFA1     : NDUFA1
    HIGD2A     : HIGD2A
    ENDOG      : ENDOG
    HOXB13     : HOXB13
    TMEM238    : TMEM238
    ZNF503     : ZNF503
    PYURF      : PYURF
    ARF6       : ARF6
    SEPHS2     : SEPHS2
    SF3B5      : SF3B5
    GTDC1      : GTDC1

references:
    dna        : /mnt/d/ubuntu/freddie-test-data/Homo_sapiens.chr21.GRCh38.dna.97.fasta
    gtf        : /mnt/d/ubuntu/freddie-test-data/Homo_sapiens.chr21.GRCh38.97.gtf
    dna_desalt : /mnt/d/ubuntu/freddie-test-data/Homo_sapiens.chr21.GRCh38.dna.97.deSALT.index/
