outpath:
    test/benchmark/

gurobi:
    license: gurobi.lic

exec:
    beds     : extern/transcript_beds.py
    coverage : extern/transcript_coverage.py
    seqpare  : extern/seqpare.sh
    pairing  : extern/seqpare_pair.py
    stats    : extern/seqpare_stats.awk

samples:
    N_sim:
        reads:
            - test/data/N_sim.fastq
        seq_type: ont1d
        data_type: sim
        gtf: whole_genome

references:
    dna_desalt   : /groups/hachgrp/annotations/DNA/97/deSALT.index

annotations:
    whole_genome : test/data/Homo_sapiens.GRCh38.97.gtf
