outpath:
    /mnt/c/Users/baraa/Documents/freddie/test/output/

gurobi:
    license: extern/gurobi.lic

samples:
    # P000S000:
    #     - test/data/H_sim.chr21.fastq
    P001S000:
        - test/data/P001S000.chr21.fastq
    # L_sim:
    #     - test/data/L_sim.chr21.fastq
    N_sim:
        - test/data/N_sim.chr21.fastq

references:
    dna        : /mnt/c/Users/baraa/Documents/freddie/test/data/Homo_sapiens.chr21.GRCh38.dna.97.fasta
    gtf        : /mnt/c/Users/baraa/Documents/freddie/test/data/Homo_sapiens.chr21.GRCh38.97.gtf
    dna_desalt : /mnt/c/Users/baraa/Documents/freddie/test/data/Homo_sapiens.chr21.GRCh38.dna.97.deSALT.index/
