outpath:
    test/dev-out/

gurobi:
    license: gurobi.lic
    timeout: 15

samples:
    N_sim:
        reads:
            - /groups/hachgrp/projects/dev-ltr-simulator/analysis/ltr-sim-dev/reads/P000S000.L-non.fastq
        seq_type: ont1d
        data_type: sim
        gtf: whole_genome

exec:
    align    : py/freddie_align.py
    split    : py/freddie_split.py
    segment  : py/freddie_segment.py
    cluster  : py/freddie_cluster.py
    isoforms : py/freddie_isoforms.py

references:
    dna_desalt : /groups/hachgrp/annotations/DNA/97/deSALT.index