outpath:
    /groups/hachgrp/projects/dev-long-iso/analysis/freddie-dev

gurobi:
    license: /groups/share/modules/gurobi811/linux64/license/gurobi.lic
    timeout: 15

samples:
    P001S000:
        - /groups/hachgrp/projects/dev-ont/raw-data/wts/fastq/P001R410/P001R410.pass.fastq
        - /groups/hachgrp/projects/dev-ont/raw-data/wts/fastq/P001R411/P001R411.pass.fastq
        - /groups/hachgrp/projects/dev-ont/raw-data/wts/fastq/P001R510/P001R510.pass.fastq
        - /groups/hachgrp/projects/dev-ont/raw-data/wts/fastq/P001R511/P001R511.pass.fastq
    N_sim:
        - /groups/hachgrp/projects/dev-ltr-simulator/analysis/ltr-sim-dev/reads/P000S000.L-non.fastq
    L_sim:
        - /groups/hachgrp/projects/dev-ltr-simulator/analysis/ltr-sim-dev/reads/P000S000.L-low.fastq
    H_sim:
        - /groups/hachgrp/projects/dev-ltr-simulator/analysis/ltr-sim-dev/reads/P000S000.L-high.fastq

exec:
    align    : py/freddie_align.py
    split    : py/freddie_split.py
    segment  : py/freddie_segment.py
    cluster  : py/freddie_cluster.py
    isoforms : py/freddie_isoforms.py
    plot     : py/freddie_plot.py

mapping_settings:
    dna  : splice
    cdna : map-ont

references:
    dna_desalt : /groups/hachgrp/annotations/DNA/97/deSALT.index/

annotations:
    gtf : /groups/hachgrp/annotations/GTF/97/Homo_sapiens.GRCh38.97.gtf
