outpath:
    /groups/hachgrp/projects/dev-long-iso/analysis/freddie-dev

gurobi_license:
    /groups/share/modules/gurobi811/linux64/license/gurobi.lic

samples:
    # P000S000:
        # - /groups/hachgrp/projects/ana-22rv1/raw-data/wts/fastq/P000R000/P000R000.pass.fastq
        # - /groups/hachgrp/projects/ana-22rv1/raw-data/wts/fastq/P000R001/P000R001.pass.fastq
        # - /groups/hachgrp/projects/ana-22rv1/raw-data/wts/fastq/P000R002/P000R002.pass.fastq
    N_sim:
        - /groups/hachgrp/projects/dev-ltr-simulator/analysis/ltr-sim-dev/reads/P000S000.L-non.fastq
    L_sim:
        - /groups/hachgrp/projects/dev-ltr-simulator/analysis/ltr-sim-dev/reads/P000S000.L-low.fastq
    N_sim:
        - /groups/hachgrp/projects/dev-ltr-simulator/analysis/ltr-sim-dev/reads/P000S000.L-high.fastq
    # P001S000:
    #     - /groups/hachgrp/projects/dev-ont/raw-data/wts/fastq/P001R410/P001R410.pass.fastq
    #     - /groups/hachgrp/projects/dev-ont/raw-data/wts/fastq/P001R411/P001R411.pass.fastq
    #     - /groups/hachgrp/projects/dev-ont/raw-data/wts/fastq/P001R510/P001R510.pass.fastq
    #     - /groups/hachgrp/projects/dev-ont/raw-data/wts/fastq/P001R511/P001R511.pass.fastq

exec:
    freddie                         : ./freddie
    gene_data                       : py/get_gene_data.py
    run_nanosim                     : py/run_nanosim.py
    split_dot                       : py/get_split_dot.py
    find_canonical_exon             : py/find_canonical_exons.py
    find_canonical_exon_iteratively : py/find_canonical_exons_iteratively.py
    find_isoforms                   : py/find_isoforms.py
    plot_isoforms                   : py/plot_isoforms.py
    disentangle                     : py/disentangle.py
    read_analysis                   : extern/nanosim/src/read_analysis.py
    simulator                       : extern/nanosim/src/simulator.py
    polyA                           : py/polyA_detection.py
    trim                            : py/polyA_trim.py
    rand_index                      : py/rand_index.py

genes:
    # AR : AR
    # MYC        : MYC
    # PLSCR3     : PLSCR3
    E2F1       : E2F1
    # ENSG00000187838     : ENSG00000187838
    # BLOC1S1    : BLOC1S1
    # SRSF2      : SRSF2
    # ATP5F1D    : ATP5F1D
    # HAX1       : HAX1
    # JTB        : JTB
    # SLC50A1    : SLC50A1
    # CTXN1      : CTXN1
    # CEBPB      : CEBPB
    # PGAM2      : PGAM2
    # GADD45GIP1 : GADD45GIP1
    # SFN        : SFN
    # NDUFA1     : NDUFA1
    # HIGD2A     : HIGD2A
    # ENDOG      : ENDOG
    # HOXB13     : HOXB13
    # TMEM238    : TMEM238
    # ZNF503     : ZNF503
    # PYURF      : PYURF
    # ARF6       : ARF6
    # SEPHS2     : SEPHS2
    # BEX1       : BEX1
    # SF3B5      : SF3B5
    # GTDC1      : GTDC1

mapping_settings:
    dna  : splice
    cdna : map-ont

references:
    dna      : /groups/hachgrp/annotations/DNA/92/Homo_sapiens.GRCh38.dna.fa
    dna_fai  : /groups/hachgrp/annotations/DNA/92/Homo_sapiens.GRCh38.dna.fa.fai
    cdna     : /groups/hachgrp/annotations/cDNA/92/Homo_sapiens.GRCh38.92.cdna.all.fa
    cdna_fai : /groups/hachgrp/annotations/cDNA/92/Homo_sapiens.GRCh38.92.cdna.all.fa.fai

annotations:
    gtf : /groups/hachgrp/annotations/GTF/92/Homo_sapiens.GRCh38.92.gtf

nanosim:
    git : https://github.com/bcgsc/NanoSim.git
    tag : v2.4-beta
