outpath:
    test/benchmark/

gurobi:
    license: gurobi.lic

exec:
    beds     : extern/transcript_beds.py
    coverage : extern/transcript_coverage.py
    seqpare  : extern/seqpare.sh
    pairing  : extern/seqpare_pair.py
    stats    : extern/seqpare_stats.awk

samples:
    ERR3588905:
        seq_type : ont1d
        ref      : drosophila_melanogaster
        reads    :
            - extern/LTR-sim/output/reads/ERR3588905.L-non.fastq

references:
    drosophila_melanogaster:
        annot      : extern/LTR-sim/refs/drosophila_melanogaster/drosophila_melanogaster.annot.gtf
        genome     : extern/LTR-sim/refs/drosophila_melanogaster/drosophila_melanogaster.dna.fa
        desalt_idx : test/mapping/drosophila_melanogaster.dna.desalt_idx
