outpath:
    /groups/hachgrp/projects/dev-long-iso/analysis/freddie-dev

samples:
    P000S000:
        - /groups/hachgrp/projects/ana-22rv1/raw-data/wts/fastq/P000R000/P000R000.pass.fastq
        - /groups/hachgrp/projects/ana-22rv1/raw-data/wts/fastq/P000R001/P000R001.pass.fastq
        - /groups/hachgrp/projects/ana-22rv1/raw-data/wts/fastq/P000R002/P000R002.pass.fastq
    P001S000:
        - /groups/hachgrp/projects/dev-ont/raw-data/wts/fastq/P001R410/P001R410.pass.fastq
        - /groups/hachgrp/projects/dev-ont/raw-data/wts/fastq/P001R411/P001R411.pass.fastq

exec:
    freddie       : ./freddie
    gene_data     : py/get_gene_data.py
    run_nanosim   : py/run_nanosim.py
    split_dot     : py/get_split_dot.py
    clustering    : py/cluster_paf.py
    meanshift     : py/mean_shift.py
    read_analysis : extern/nanosim/src/read_analysis.py
    simulator     : extern/nanosim/src/simulator.py

genes:
    MYC     : MYC
    PLSCR3  : PLSCR3
    E2F1    : E2F1
    EEF1A1  : EEF1A1
    BLOC1S1 : BLOC1S1
    SRSF2   : SRSF2
    # TYMS    : TYMS
    # HES4    : HES4
    ATP5F1D : ATP5F1D
    HAX1    : HAX1
    JTB     : JTB
    SLC50A1 : SLC50A1

references:
    genome : /groups/hachgrp/annotations/DNA/92/Homo_sapiens.GRCh38.dna.fa

annotations:
    gtf : /groups/hachgrp/annotations/GTF/92/Homo_sapiens.GRCh38.92.gtf

url:
    nanosim : https://github.com/bcgsc/NanoSim/archive/77a4393e18c67adddf60427a617499ac352bc9d8.zip
