outpath:
    test/dev-out/

gurobi:
    license: /home/baraa/gurobi.lic
    timeout: 15

samples:
    N_sim.chr21:
        reads:
            - test/data/N_sim.chr21.fastq
        seq_type: ont1d
    # L_sim.chr21:
    #     reads:
    #         - test/data/L_sim.chr21.fastq
    #     seq_type: ont1d
    # P000S000.chr21:
    #     reads:
    #         - test/data/P000S000.chr21.fastq
    #     seq_type: ont1d
    # P001S000.chr21:
    #     reads:
    #         - test/data/P001S000.chr21.fastq
    #     seq_type: ont1d
    # P001S000:
    #     reads:
    #         - /groups/hachgrp/projects/dev-ont/raw-data/wts/fastq/P001R410/P001R410.pass.fastq
    #         - /groups/hachgrp/projects/dev-ont/raw-data/wts/fastq/P001R411/P001R411.pass.fastq
    #         - /groups/hachgrp/projects/dev-ont/raw-data/wts/fastq/P001R510/P001R510.pass.fastq
    #         - /groups/hachgrp/projects/dev-ont/raw-data/wts/fastq/P001R511/P001R511.pass.fastq
    #     seq_type: ont1d
    # N_sim:
    #     reads:
    #         - /groups/hachgrp/projects/dev-ltr-simulator/analysis/ltr-sim-dev/reads/P000S000.L-non.fastq
    #     seq_type: ont1d
    # L_sim:
    #     reads:
    #         - /groups/hachgrp/projects/dev-ltr-simulator/analysis/ltr-sim-dev/reads/P000S000.L-low.fastq
    #     seq_type: ont1d
    # H_sim:
    #     reads:
    #         - /groups/hachgrp/projects/dev-ltr-simulator/analysis/ltr-sim-dev/reads/P000S000.L-high.fastq
    #     seq_type: ont1d

exec:
    align      : py/freddie_align.py
    split      : py/freddie_split.py
    segment    : py/freddie_segment.py
    cluster    : py/freddie_cluster.py
    isoforms   : py/freddie_isoforms.py
    beds       : py/freddie_beds.py
    similarity : py/freddie_similarity.py
    summarize  : py/freddie_summarize.py
    plot       : py/freddie_plot.py

references:
    dna_desalt : test/data/Homo_sapiens.chr21.GRCh38.dna.97.deSALT.index

annotations:
    gtf : test/data/Homo_sapiens.chr21.GRCh38.97.gtf
