outpath:
    .

samples:
    22RV1.pcr-free-cDNA.ONT.180525: /groups/hachgrp/projects/long-iso/raw-data/22RV1.pcr-free-cDNA.ONT.180525/fastq/22RV1-cDNA-180525.pass.fastq
    22RV1.pcr-free-cDNA.ONT.180528: /groups/hachgrp/projects/long-iso/raw-data/22RV1.pcr-free-cDNA.ONT.180528/fastq/22RV1-cDNA-180528.pass.fastq
    22RV1.pcr-free-cDNA.ONT.180807: /groups/hachgrp/projects/long-iso/raw-data/22RV1.pcr-free-cDNA.ONT.180807/fastq/22RV1-cDNA-180807.pass.fastq

exec:
    freddie: ./freddie
    gene_data: py/get_gene_data.py
    nanosim_tsv: py/get_nanosim_tsv.py
    read_analysis: extern/nanosim/src/read_analysis.py
    simulator: extern/nanosim/src/simulator.py

genes:
    AR: AR
    PLSCR3: PLSCR3
    E2F1: E2F1

references:
    genome: /groups/hachgrp/annotations/DNA/92/Homo_sapiens.GRCh38.dna.fa

annotations:
    gtf: /groups/hachgrp/annotations/GTF/92/Homo_sapiens.GRCh38.92.gtf

url:
    nanosim: https://github.com/bcgsc/NanoSim/archive/77a4393e18c67adddf60427a617499ac352bc9d8.zip
