name: freddie
channels:
  - conda-forge
  - bioconda
  - defaults
  - anaconda
  - gurobi
dependencies:
  - python>=3.6
  - snakemake>=5
  - desalt=1.5.4
  - pysam>=0.15
  - numpy>=1.16
  - scikit-learn>=0.20
  - scipy>=1.2.1
  - networkx>=2
  - gurobi>=9.0
  - matplotlib>=3
  - pypdf2>=1.26
